version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    
  db:
    image: postgres:12.4
    restart: always
    container_name: db
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    restart: always
    build:
      context: ./kanal_servis
    expose:
      - 8000
    volumes:
      - static_value:/app/static/
    depends_on:
      - db
      - redis
    command: >
      sh -c "python3 manage.py makemigrations google_sheets
             python3 manage.py migrate --no-input
             python3 manage.py collectstatic --no-input
             gunicorn kanal_servis.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./.env

  celery:
    build: ./kanal_servis
    command: celery -A kanal_servis worker -l info
    volumes:
      - ./kanal_servis:/app
    depends_on:
      - redis
    env_file:
      - ./.env

  celery-beat:
    build: ./kanal_servis
    command: celery -A kanal_servis beat -l info
    volumes:
      - ./kanal_servis:/app
    depends_on:
      - redis
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  result_build: